Fix POP::kids-expected parameter computation
... for single worker, single disker use case.

A single worker (i.e. the default) alone does not imply "no Coordinator
or diskers". It does not really imply anything special as far as kid
counting is concerned! The bug went unnoticed because popular tests
either enable no dedicated diskers and no workers OR enable a disker and
multiple workers. The bug was exposed by truncated-responses tests that
enabled a disker without enabling multiple workers:

    Error: Proxy Overlord communication failure (555):
    unexpected kids: 2 >= 0

----

Merged related SQUID-659-truncated-responses changes (as of 8778fb0).