Support Node v24 and require modern Node releases
Motivation: Node v20 is "out of maintenance" since March 2026. GitHub
Actions will be forced to run with Node.js 24 by default starting June
2, 2026; GitHub will then remove Node.js 20 from our Linux runners (at
least) on September 16, 2026. GitHub Actions have warned about Node v20
deprecation for a while.

When running a Daft test in a GitHub Actions environment that uses
Node.js v24:

    .../daft/node_modules/esm/esm.js:1
        const __global__ = this;...
        TypeError: Function.prototype.apply was called on undefined,
            which is a undefined and not a function
        at Object.<anonymous> (.../daft/src/cli/daft.js:7:18)
        at Module._compile (node:internal/modules/cjs/loader:1830:14)

Node v24 supports ES6 modules (ESM) natively and no longer supports our
esm package-based hacks that enabled that module support for earlier
nodejs releases. Node issues/tickets discussing related changes claim
that the esm package itself has not been maintained for a long time.
Removal of those hacks probably implies that Daft will no longer work
with older Node releases that do not support ES6 modules natively!

Using native ESM support required significant changes:

* Manually populating module.exports in src/misc/Config.js no longer
  worked. Config.js module now focuses on exporting an Api class object.
  The class itself is dynamically assembled to have methods that match
  supported options. That export was the only way I could find to avoid
  changing 60+ known Config.foo() calls in Daft and test plot code. Also
  adjusted misc/Config importing statements to work with that new
  single-object exporting code. The module still exports a lot of
  functions (while also providing them as Api methods), but that is just
  a diff-reduction trick. I suspect that we can significantly improve,
  including simplify, misc/Config code further by fully converting old
  module.exports-targeting code to use the new Api class/approach.

* Our Babel-driven eslint integration no longer worked. I removed
  babel-related packages and upgraded eslint to work without Babel. That
  upgrade required switching to new config format -- eslint.config.mjs.

* Module import statements must use explicit filename extensions now. We
  could rename module files to use an ".mjs" extension, but that would
  rename virtually every Daft source code file! Instead, `package.json`
  now uses `"type": "module"` setting to force Node to treat our `.js`
  modules as ES6 modules. This is an officially recommended solution.

Side effects:

* Checking whether a legacy Config.Foo option was set/defined no longer
  works. I found only one such use case -- Config.Tests -- and adjusted
  it to use Config.isExplicitlySet() API. I am not sure the two are
  equivalent, but I hope that the replacement is not going to break test
  plots that generate `--tests` options. I am not aware of any.

* Ordered import statements (like a dumb editor would). They had to be
  modified to add extensions anyway, and having one simple order may
  help keep the importing statement order consistent across modules...

* Also upgraded the "optionator" package to the latest version: v0.9.4.

* Removal of Babel and "npm update" should address several
  vulnerabilities in our dependencies (as flagged by GitHub Dependabot).

Test plots will need similar adjustments.