Make the proxy listening address configurable; default to 127.0.0.1
We were using "::" in hope to auto-support both IPv4 and IPv6 proxies,
but it required complicated documentation and did not work well in some
environments. For example, on Ubuntu 22.04 with IPv6 enabled, the client
got ECONNREFUSED errors when trying to connect to an IPv4-only proxy:

    Error: connect ECONNREFUSED :::3128